# .github/release.yml

changelog:
  exclude:
    labels:
      - Ignore-For-Release
  categories:
    - title: Breaking Changes 🚨
      labels:
        - Breaking-Change
    - title: Exciting New Features 🎉
      labels:
        - New-Feature
    - title: Improvement 🌱
      labels:
        - Enhancement
    - title: Bug Fixes 🛠
      labels:
        - Bug-Fixes
    - title: Other Changes 📚
      labels:
        - "*"
