# .github/release.yml

changelog:
  exclude:
    labels:
      - Ignore-For-Release -
      - EFR -
  categories:
    - title: Breaking Changes 🚨
      labels:
        - Breaking-Change -
    - title: Exciting New Features 🎉
      labels:
        - New-Feature -
        - Add -
    - title: Improvement 🌱
      labels:
        - Enhancement -
        - Improve -
    - title: Bug Fixes 🛠
      labels:
        - Bug-Fixes -
        - Bugfix -
    - title: Other Changes 📚
      labels:
        - "*"