name: Add links on release
on:
    release:
        types: [created]
jobs:
    debug:
      name: Debug
      runs-on: ubuntu-latest
      steps:
        - name: Edit Release
          uses: irongut/EditRelease@v1.2.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            id: ${{ github.event.release.id }}
            name: "Beta"
            body: "<details>\n<summary>Click me</summary>  ### Heading\n</details>"
