name: Add links on release
on:
  push:
  release:
    types: [created]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Replace characters in file
        id: create-markdown-text
        run: |
          x=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          sed "s/{version}/$x/g" ./.github/releaseLinkTemplate.md > ./temp_releaseLinkTemplate.md

      - name: validate
        run: echo "${{ steps.create-markdown-text.outputs.MARKDOWN }}"

      - name: Edit Release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          files: "temp_releaseLinkTemplate.md"
