name: Add links on release
on:
  release:
    types: [created]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create markdown download links
        run: |
          # Remove the prefix'v' from version
          RELEASE_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')

          # Replace the place hholders with the actual release version
          sed "s/{version}/$RELEASE_VERSION/g" ./.github/releaseLinkTemplate.md > ./temp_releaseLinkTemplate.md

      - name: Add links to release notes
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "temp_releaseLinkTemplate.md"
          append_body: true
